### ISSUE TITLE
syslog is not working

### ISSUE THREAD

**Issue by ADeeeee** [CommunityHoneyNetwork/hpfeeds-logger#39]
Hi folks,

I've run the hpfeeds-logger container and it does works with the filelogs while I'm touching the sensors, but not for the syslog part. The graylog doesn't receive any requests just from v.1.9.1 one. The container is running without any errors and it's using the the json file with the correct setting. Is there a debug mode or logs for the syslog?

**Enviroment:**
Ubuntu 18.04 LTS
Docker version 19.03.13, build 4484c46d9d
docker-compose version 1.27.4, build 40524192

**Container version:**
v.1.9.1 besides the upstream ones

**Logs from the container:**
```
2020-11-20 10:04:31,317 - INFO - __main__[31][hpfeeds-logger] - Parsing config file: /opt/hpfeeds-logger/logger.json
2020-11-20 10:04:31,317 - INFO - __main__[92][hpfeeds-logger] - Writing events to /var/log/hpfeeds-logger/chn-splunk.log using strategy size
2020-11-20 10:04:31,319 - INFO - __main__[106][hpfeeds-logger] - Writing syslog events to x.x.x.x
2020-11-20 10:04:31,322 - INFO - __main__[118][hpfeeds-logger] - connected to hpfeeds
```

**Comment by JesseBowling** [comment]
Hi @ADeeeee !

Thank you for the details of your setup and filing an issue!

You can add a `DEBUG=true` to your hpfeeds-logger.env file to get additional messages. Looking at the code, I'm not sure this will help sepcifically for the syslog portion, as there aren't any debug statements for the setup. Fundamentally the syslog output is simply an additional Python.logging handler added during setup. 

```
        if config['syslog'] and config['syslog']['syslog_enabled']:
            syslog_host = config['syslog']['syslog_host'] or "localhost"
            syslog_port = config['syslog']['syslog_port'] or 514
            syslog_facility = config['syslog']['syslog_facility'] or "user"
            syslog_handler = SysLogHandler(address=(syslog_host, syslog_port),
                                           facility=syslog_facility)
            syslog_handler.setFormatter(logging.Formatter('%(message)s'))
            data_logger.addHandler(syslog_handler)
            logger.info('Writing syslog events to %s', syslog_host)
```

Also not sure if you upgraded or if this is a fresh installation, but I'd be sure you don't have any quoted variables in your .env files. You can also try a `docker-compose exec hpfeeds-logger cat /opt/hpfeeds-logger/logger.json` and examine that file to be sure all your variables have been passed in correctly. (watch out for invalid JSON config!)

Are you getting any logs to the file if you enable `FILELOG_ENABLED=true`? If you are, then it's most likely an issue with host networking or the syslog receiving side. 

Another good test would be to tcpdump the data coming out of the container...

```
docker-compose exec hpfeeds-logger bash
```
(then from in the container)
```
apt update && apt install -y tcpdump
tcpdump -i any -nn port 514
```
Substitute SYSLOG_PORT for 514 in the above command if you're using a different port..

**Comment by ADeeeee** [comment]
Hi Jesse,

I just fixed it. Thanks again for the recommandation which really helps a lot. Just realized the image is based on ubuntu...my bad. 

First of all, it's a fresh installation and migrated all the settings manually from v1.8, including custom ones (e.g. macvlan...). Actually, all the elements are working great. Just messed up the pipleline in Graylog, which is the root cause in my case, but there're something I'd like to share with you:

1. 
> You can add a `DEBUG=true` to your hpfeeds-logger.env file to get additional messages. Looking at the code, I'm not sure this will help sepcifically for the syslog portion, as there aren't any debug statements for the setup. Fundamentally the syslog output is simply an additional Python.logging handler added during setup.

Tried and which doesn't work at all. I've read the code and there seems no debug mode for hpfeeds-logger. It'd be nice to have one without installing debug tools in a container. It's good while there's less binaries / tools in the containers.

2.
> Release node from v1.9:
> Improved logging (username/password logs from Dionaea, hpfeeds-logger support for syslog and file logging in single container, etc.)

Didn't know that the log format was also changed, including the order of the raw data. It'd be nice if it's mentioned in the note because it looks really alike in output or logfile.

3. 
Good news. The timestamp has worked like a charm with Graylog since the changes from v1.8. 

4. 
The timestamp has worked like a charm since the changes from v1.8. 
By the way, the document with v1.9.1 tag is wrong. You can see the docker-compose.yml files are still using v1.9. The other tags are correct.
https://communityhoneynetwork.readthedocs.io/en/v1.9.1/serverinstall/

Please let me know if you need any information.

**Comment by JesseBowling** [comment]
> Hi Jesse,
> 
> I just fixed it. Thanks again for the recommandation which really helps a lot. Just realized the image is based on ubuntu...my bad.
> 
> First of all, it's a fresh installation and migrated all the settings manually from v1.8, including custom ones (e.g. macvlan...). Actually, all the elements are working great. Just messed up the pipleline in Graylog, which is the root cause in my case, but there're something I'd like to share with you:

I'm glad you're fixed up!

> > You can add a `DEBUG=true` to your hpfeeds-logger.env file to get additional messages. Looking at the code, I'm not sure this will help sepcifically for the syslog portion, as there aren't any debug statements for the setup. Fundamentally the syslog output is simply an additional Python.logging handler added during setup.
> 
> Tried and which doesn't work at all. I've read the code and there seems no debug mode for hpfeeds-logger. It'd be nice to have one without installing debug tools in a container. It's good while there's less binaries / tools in the containers.
> 

After I made this update I went and discovered the same thing! There's really just not much more debug that can be turned on in hpfeeds-logger. That said, I did add in support to actually pass that variable into the container in a useful way, and added a couple more messages there. I also added a lot more messages in hpfeeds3/mnemosyne as well, and have started working on getting those settings to flow into sub-packages/loaded modules. It will be a haul, but you should see some improvements by 1.9.2. :)

> > Release node from v1.9:
> > Improved logging (username/password logs from Dionaea, hpfeeds-logger support for syslog and file logging in single container, etc.)
> 
> Didn't know that the log format was also changed, including the order of the raw data. It'd be nice if it's mentioned in the note because it looks really alike in output or logfile.
> 

Yes, the ordering bit I didn't think was needed, but I'll include that in the future..it was related to the timestamp work...

> 
> Good news. The timestamp has worked like a charm with Graylog since the changes from v1.8.
> 
> 
> The timestamp has worked like a charm since the changes from v1.8.

I previously adjust the Splunk formatter to generate a timestamp at the front of the message (to ensure Splunk can ingest the logs correctly) and needed to do the same for the JSON output (again, Splunk gets confused about dates if it doesn't find the timestamp early in the line). :(

> By the way, the document with v1.9.1 tag is wrong. You can see the docker-compose.yml files are still using v1.9. The other tags are correct.
> https://communityhoneynetwork.readthedocs.io/en/v1.9.1/serverinstall/
> 

Yep, found that one by chance the other day! Fixed in master and will make it to stable RSN. :)

> Please let me know if you need any information.

No, but I appreciate your participation and willingness to share issues! This sort of feedback is very useful for the team! Please keep it coming!

Cheers!
